name: Install Node.js and npm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
        working-directory: ./home/sgadmin/ # Adjust if needed

      # Step 4: Verify installation
      - name: Verify installation
        run: |
          npm --version
          node --version
